// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CleanupAssets(arg1) {
  return window['go']['main']['App']['CleanupAssets'](arg1);
}

export function DownloadAsset(arg1, arg2) {
  return window['go']['main']['App']['DownloadAsset'](arg1, arg2);
}

export function FetchPlaylist() {
  return window['go']['main']['App']['FetchPlaylist']();
}

export function GetBuildNumber() {
  return window['go']['main']['App']['GetBuildNumber']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function SetDevMode(arg1) {
  return window['go']['main']['App']['SetDevMode'](arg1);
}
