// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from "../models";

export function FetchPlaylist(): Promise<Array<main.Ad>>;
export function DownloadAsset(arg1: string, arg2: string): Promise<string>;
export function CleanupAssets(arg1: Array<string>): Promise<void>;
export function IsDevMode(): Promise<boolean>;
