// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CleanupAssets(arg1:Array<string>):Promise<void>;

export function DownloadAsset(arg1:string,arg2:string):Promise<string>;

export function FetchPlaylist():Promise<Array<main.Ad>>;

export function GetBuildNumber():Promise<string>;

export function IsDevMode():Promise<boolean>;
